kpop:
  outputs:
    dev:
      account: yd48127.ap-northeast-2.aws
      database: dev
      password: "{{ env_var('DBT_ENV_SECRET_PASSWORD') }}"
      role: accountadmin
      schema: public
      threads: 200
      type: snowflake
      user: "{{ env_var('DBT_ENV_SECRET_USER') }}"
      warehouse: snowflake
  target: dev
